### PR TITLE
154 redesign author box

### LINKED ISSUE #154: Redesign author box that goes underneath posts and on author pages
**Problems with current author box:**
- ~~Broken image for every author who hasn't set a profile picture~~
- Perhaps not an ideal background color
- Box/font size too large

**Other potential improvements:**
- Social media icons with links to author's accounts if provided by author
- Link to "Read more from this author" or such since it may not be obvious that clicking name leads to author page
- Separately, an option to "Read more" of the author's bio (see below) so long bios don't make author box too large
Screen Shot 2020-10-25 at 6 22 58 PM

**Getting started:**
- Make sure to do "git pull" on your local main branch of stanforddaily and then create a new branch off of it (type "git branch [NEW_BRANCH_NAME]" and then "git checkout [NEW_BRANCH_NAME]") for this ticket. I recommend naming the new branch something like "154-redesign-author-box" to capture the ticket number and a brief description. This is a good practice, especially on larger dev teams like the one you might work on someday!
- Navigate to the file called "AuthorBox.tsx" in the "components" folder.
- The file will be confusing at first. But don't worry! You won't need to mess with much of it.
- You can see the author box in action by running the commands "yarn" and then "yarn start" from the stanforddaily folder in your terminal and then going to the end of an article or an author's page at localhost:3000.
- Try typing text in a pair of `<p>` or `<h1>` tags on line 62 and see it appear in the author box at localhost:3000. Pretty cool!

### PR DESCRIPTION
**Pull request by sbcatania**
## Reasons for making this change

Added additional author fields

## Related tickets

Fixes #154

## Screenshots

Screen Shot 2021-06-26 at 4 56 06 PM

### CODE REVIEW

File: components/AuthorBox.tsx [hunk 1]
```diff
@@ -28,9 +47,16 @@ const AuthorBox: React.ElementType<AuthorBoxProps> = ({
   axios
     .get("https://wp.stanforddaily.com/wp-json/tsd/v1/authors/" + id + "/")
     .then(response => {
+      console.log(response);
       setAdditionalAuthorInfo(response.data);
     });
 
+  // set object returns to local variables
+  const emailURL = "mailto:" + additionalAuthorInfo?.email;
+  const twitterURL = "https://www.twitter.com/" + additionalAuthorInfo?.twitter;
```
Comment (epicfaace) [inline components/AuthorBox.tsx:56]:
```suggestion
  const twitterURL = "https://www.twitter.com/" + encodeURIComponent(additionalAuthorInfo?.twitter);
```

File: components/AuthorBox.tsx [hunk 2]
```diff
@@ -28,9 +47,16 @@ const AuthorBox: React.ElementType<AuthorBoxProps> = ({
   axios
     .get("https://wp.stanforddaily.com/wp-json/tsd/v1/authors/" + id + "/")
     .then(response => {
+      console.log(response);
       setAdditionalAuthorInfo(response.data);
     });
 
+  // set object returns to local variables
+  const emailURL = "mailto:" + additionalAuthorInfo?.email;
```
Comment (epicfaace) [inline components/AuthorBox.tsx:55]:
```suggestion
  const emailURL = "mailto:" + encodeURIComponent(additionalAuthorInfo?.email);
```

File: components/AuthorBox.tsx [hunk 3]
```diff
@@ -62,10 +88,51 @@ const AuthorBox: React.ElementType<AuthorBoxProps> = ({
...
         />
+        <View
+          style={{
+            flexDirection: "row",
+            display: "flex",
+            justifyContent: "center",
+            marginLeft: 12.5,
+          }}
+        >
+          {(additionalAuthorInfo?.email && !additionalAuthorInfo.email.includes("@stanford.edu")) ||
```
Comment (epicfaace) [inline components/AuthorBox.tsx:99]:
```suggestion
          {(additionalAuthorInfo?.email && !additionalAuthorInfo.email.endsWith("@stanford.edu")) || 
```

**Review by epicfaace — COMMENTED** [review]
We should remove .DS_Store -- and maybe add it to .gitignore

File: components/AuthorBox.tsx [hunk 4]
```diff
@@ -28,9 +47,16 @@ const AuthorBox: React.ElementType<AuthorBoxProps> = ({
   axios
     .get("https://wp.stanforddaily.com/wp-json/tsd/v1/authors/" + id + "/")
     .then(response => {
+      console.log(response);
```
Comment (hs4man21) [inline components/AuthorBox.tsx:50]: Let's remove this before merging

File: components/AuthorBox.tsx [hunk 5]
```diff
@@ -28,9 +47,16 @@ const AuthorBox: React.ElementType<AuthorBoxProps> = ({
...
       setAdditionalAuthorInfo(response.data);
     });
 
+  // set object returns to local variables
+  const emailURL = "mailto:" + encodeURIComponent(additionalAuthorInfo?.email);
```
Comment (hs4man21) [inline components/AuthorBox.tsx:55]: Can we change all instances of `.email` to `.dailyEmail`? Made this change on the backend

File: components/PostFooterBox.tsx [hunk 6]
```diff
@@ -94,15 +94,18 @@ const PostFooterBox: React.ElementType = () => {
...
         experience in journalism, digital media and business for the next
         generation of reporters. Your support makes a difference in helping give
         staff members from all backgrounds the opportunity to develop important
         professional skills and conduct meaningful reporting. All contributions
         are tax-deductible.
       </p>
-
       <DonationForm />
       <br></br>
       <TextButtonWithLink
```
Comment (hs4man21) [inline components/PostFooterBox.tsx:111]: Do we want the changes in this file?

File: components/AuthorBox.tsx [hunk 7]
```diff
@@ -62,10 +88,51 @@ const AuthorBox: React.ElementType<AuthorBoxProps> = ({
...
         />
+        <View
+          style={{
+            flexDirection: "row",
+            display: "flex",
+            justifyContent: "center",
+            marginLeft: 12.5,
+          }}
+        >
+          {(additionalAuthorInfo?.email && !additionalAuthorInfo.email.endsWith("@stanford.edu")) ||
```
Comment (hs4man21) [inline components/AuthorBox.tsx:99]: We can remove the `.endsWith` logic here per the above change

**Review by hs4man21 — CHANGES_REQUESTED** [review]

File: components/PostFooterBox.tsx (hunk 6 above)
Comment (sbcatania) [reply components/PostFooterBox.tsx:111]: Yes, I cleaned up the design a tiny bit. Removed the red line at the top since I thought it was ugly and changed the spacing to make it a bit more compact.

File: components/AuthorBox.tsx (hunk 7 above)
Comment (sbcatania) [reply components/AuthorBox.tsx:99]: Done

Comment (sbcatania) [reply components/AuthorBox.tsx:99]: Wait where is the above change? Is it on the backend?

File: components/AuthorBox.tsx (hunk 4 above)
Comment (sbcatania) [reply components/AuthorBox.tsx:50]: Just the console.log right? Just took that out.

File: components/AuthorBox.tsx (hunk 7 above)
Comment (hs4man21) [reply components/AuthorBox.tsx:99]: The change mentioned above changing `email` field to `dailyEmail`, yeah

Comment (sbcatania) [reply components/AuthorBox.tsx:99]: Also I think we need to remove the entire second half of the && right

Comment (hs4man21) [reply components/AuthorBox.tsx:99]: Yeah, that's what I meant by the `.endsWith` logic, sorry

File: components/AuthorBox.tsx (hunk 4 above)
Comment (hs4man21) [reply components/AuthorBox.tsx:50]: Yup

**Review by hs4man21 — APPROVED** [review]
